### ISSUE TITLE
Custom Template Deployment Not Working on Ibiza Portal

### ISSUE THREAD

**Issue by mjalloul** [Azure/azure-quickstart-templates#386] opened 2015-07-11 19:09 UTC
This is not a GitHub repo issue per se, but it's a bit related. Here's the issue:

>Clicking on the **Deploy to Azure** button from both the GitHub repo or the templates gallery on http://azure.microsoft.com/en-us/documentation/templates/ has not been working since early this morning (7/11/2015). The original URL (e.g.: https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fazure-quickstart-templates%2Fmaster%2Fdocker-simple-on-ubuntu%2Fazuredeploy.json) which typically resulted in the custom template being loaded into the portal blade is now getting redirected to the blank template instead (https://portal.azure.com/#create/Microsoft.Template).

FYI, here's what the experience currently looks like after clicking on the **Deploy to Azure** button:
![deploymenttemplateportalissue-7-11-2015-1](https://cloud.githubusercontent.com/assets/8796785/8634995/412db260-27c5-11e5-9adb-c920b3e703a0.png)

And this is what it looks like after clicking on the **Create** button:
![deploymenttemplateportalissue-7-11-2015-2](https://cloud.githubusercontent.com/assets/8796785/8634994/412b2b6c-27c5-11e5-99b6-344171ce0f27.png)

**Comment by rgardler** [comment] 2015-07-11 19:32
I have confirmed this behavior and reported it to the appropriate team in MS. Thank you for the report.

As a temporary workaround you can paste the template json file into the edit window picrured above, click save and then proceed as normal.

Sent from my Windows Phone
________________________________

**Comment by gurua** [comment] 2015-07-11 22:37
Thanks for reporting the issue. The issue is being investigated actively.

**Comment by gurua** [comment] 2015-07-11 23:58
A fix has been pushed for this issue. Please let us know if you are still seeing an issue.

**Comment by mjalloul** [comment] 2015-07-12 00:17
Thanks for the super quick turnaround. I've verified that the issue is indeed fixed.

**Comment by rgardler** [comment] 2015-07-12 01:25
@gurua thank you for the rapid response. It is indeed fixed. Closing this issue.

**Closed by rgardler** 2015-07-12 01:25 UTC
