### ISSUE TITLE
201-aci-sftp-files/azuredeploy.json

### ISSUE THREAD

**Issue by jikuja** [Azure/azure-quickstart-templates#8622] opened 2020-12-18 18:27 UTC
[Template Name goes here](Template link goes here)

### Issue Details
Template does not work because of comments and/or multiline strings added with the latest commit.

### Repro steps (*if necessary, delete otherwise*)
1. Click deploy to azure in https://github.com/Azure/azure-quickstart-templates/tree/master/201-aci-sftp-files
2. Portal gives the error `Error parsing template. Please ensure the template is valid JSON. Unexpected end of string at character position 4327. (28 other errors)` Matches to multiline string

CC: @MCKLMT

**Comment by MCKLMT** [comment] 2020-12-18 19:31
Thanks for bringing this to my attention. I created a pull request to solve the issue. In the meantime, you can get the corrected template and submit it using the portal, Azure Powershell or CLI.

**Comment by MCKLMT** [comment] 2020-12-22 17:48
The pull request has been merged and the issue is now solved.
@jikuja Can you check on your side?

**Closed** 2021-01-05 16:10 UTC
