### ISSUE TITLE
unable to create VMs using this template

### ISSUE THREAD

**Issue by vijayasekharn** [Azure/azure-quickstart-templates#8411] opened 2020-10-10 05:27 UTC
when i click on "deploy to azure" (https://azure.microsoft.com/en-us/resources/templates/sccm-currentbranch/), its opening the azure portal and getting below error. could you please help me with this issue?

<img width="935" alt="AzureTemplateErro JPG" src="https://user-images.githubusercontent.com/29273876/95646565-508be280-0ae7-11eb-8a7d-a2b534feaece.png">

**Comment by Yvand** [comment] 2020-10-13 12:55
Duplicate of https://github.com/Azure/azure-quickstart-templates/issues/8288.
This issue affects all the templates. As a workaround, you can use the same format for the URI as described in comment https://github.com/Azure/azure-quickstart-templates/issues/8288#issuecomment-703684266

**Comment by bmoore-msft** [comment] 2020-10-22 02:26
@Yvand - thx...

**Closed by bmoore-msft** 2020-10-22 02:26 UTC
