### ISSUE TITLE
sharepoint-three-vm - Deploying Issue Create SQL

### ISSUE THREAD

**Issue by ng25** [Azure/azure-quickstart-templates#2068] opened 2016-06-06 07:06 UTC
sharepoint-three-vm https://github.com/Azure/azure-quickstart-templates/tree/master/sharepoint-three-vm

### Issue Details

I started deploying this template. All steps are green and the servers have been created, except the SQL Server. I received the following error.
Any idea how to proceed?

Thanks in advance for your help.

Operation Id
14D91EB3779CDA8C
Tracking Id
29f9c445-97cd-4a5d-b3cd-2e8db204a955
Status
Conflict
Provisioning State
Failed
Timestamp
6/3/2016, 3:11:08 PM
Duration
PT41M8.2818726S
Type
Microsoft.Resources/deployments
Resource Id
/subscriptions/f885df16-1de7-4489-a891-a45f56992739/resourceGroups/spfarmresource/providers/Microsoft.Resources/deployments/ProvisioningSQLServerVM
StatusMessage
{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see http://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "Conflict",
            "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'CreateSQLServer'. Error message: \\\"Error downloading https://download.microsoft.com/download/9/1/7/91772932-6DA4-48FD-9B1F-DA2C7EAEE35B/Windows8.1-KB3000850-x64.msu: Exception calling \\\"DownloadFile\\\" with \\\"2\\\" argument(s): \\\"Unable to connect to the remote server\\\"\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}
Resource
ProvisioningSQLServerVM

**Comment by simongdavies** [comment] 2016-06-10 05:06
@ng25 Thanks for reporting this, this error is caused by an issue in the DSC extension which has been addressed in the latest version, the templates need updating to take advantage of this. I will do this in the next few days, in the meantime resubmitting may be successful

**Closed** 2016-06-15 05:34 UTC
Labels: bug
