### ISSUE TITLE
mesos-swarm-marathon/configure-mesos-cluster.sh failure

### ISSUE THREAD

**Issue by jparkerCAA** [Azure/azure-quickstart-templates#677] opened 2015-10-01 22:58 UTC
It appears that the latest marathon deb package has a bad dependency. 

```The following packages have unmet dependencies:
 marathon : Depends: java8-runtime-headless but it is not installable
E: Unable to correct problems, you have held broken packages.```

this causes the cluster config script to fail

**Comment by rgardler** [comment] 2015-10-02 20:30
Thanks for reporting this issue. I have reproduced it and am looking into it further.

**Comment by rgardler** [comment] 2015-10-05 15:49
Upstream cause: https://github.com/mesosphere/marathon/issues/2357

Need to install openjdk-8-jre

**Comment by singhkay** [comment] 2015-10-07 23:29
Closing since the fix PR is merged

**Comment by donigian** [comment] 2015-11-29 21:46
Resolution doesn't work:
```
sudo aptitude install openjdk-8-jre
Couldn't find any package whose name or description matched "openjdk-8-jre"
Couldn't find any package whose name or description matched "openjdk-8-jre"
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.
```

**Comment by singhkay** [comment] 2015-11-30 18:25
@rgardler @anhowe - Can you take a look at this?

**Comment by singhkay** [comment] 2016-04-08 21:36
Closing since the template was removed

**Closed by singhkay** 2016-04-08 21:36 UTC
Labels: bug
