### ISSUE TITLE
ARM template for adding existing key to azure keyvault

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/azure-quickstart-templates#1349] opened 2016-03-08 16:45 UTC
Hi,

I like to add the PEM key from local to the azure key vault using resource manager templates, but I dont find any good references.
I use below json snippet to add secrets in existing vault

"resources": [
{
"type": "Microsoft.KeyVault/vaults/secrets",
"apiVersion": "2015-06-01",
"name": "[concat(parameters('keyVaultName'), '/', parameters('secretName'))]",
"properties": {
"value": "[parameters('secretValue')]"
}
},
{
"type": "Microsoft.KeyVault/vaults/keys",
"apiVersion": "2015-06-01",
"name": "[concat(parameters('keyVaultName'), '/', parameters('keyName'))]",
"properties": {
"value": "[parameters('keyValue')]"
}
}
]

And the parameter json is:
{
"$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
"contentVersion": "1.0.0.0",
"parameters": {
"keyVaultName": {
"value": "myvault1"
},
"secretName": {
"value": "mypassword"
},
"secretValue": {
"value": "test"
}
}
}

Similarly, I have a local PEM file which needs to be added in vault using template. can you help me the syntax for referencing "keyValue" to local PEM in parameters file.

**Comment by singhkay** [comment] 2016-03-08 18:15
Closing as a dupe of #1350

**Closed by singhkay** 2016-03-08 18:15 UTC

**Comment by SPSCS-Simon** [comment] 2022-09-09 17:44
@singhkays per @sjpb comment folks are look for the "setting" a secret into an exiting key vault incrementally that's not defined in the current template. Please Re-open. Also the link "retrieving" issue now has broken links.
