### ISSUE TITLE
Redis cache template enable diagnostics doesn't work

### ISSUE THREAD

**Issue by lmillott** [Azure/azure-quickstart-templates#1921] opened 2016-05-05 22:11 UTC
[101-redis-cache](https://github.com/Azure/azure-quickstart-templates/blob/master/101-redis-cache/azuredeploy.json)

### Issue Details
When I deploy this template with diagnostics turned on, diagnostics still shows up as "OFF" in the azure portal.

### Repro steps
1. Deploy the template with diagnosticsStatus = ON and existingDiagnosticsStorageAccountName = (your storage account name)
2. Visit the redis cache in the azure portal and observe that diagnostics is turned off.
3. Manually turn on diagnostics with the same settings and it works fine.

**Comment by singhkay** [comment] 2016-05-17 23:09
@steved0x Can you take a look at this?

**Comment by steved0x** [comment] 2016-05-18 14:06
@singhkay I am taking a look.

**Comment by steved0x** [comment] 2016-05-18 14:32
@singhkay I can't reproduce the issue (the cache created with diagnostics enabled and designated with my storage account) but I am following up with the cache team to see if they have any feedback or ideas.

**Comment by singhkay** [comment] 2016-05-18 22:50
Thanks @steved0x. @lmillott Will close this in the meantime, feel free to reopen if this is still an issue.

**Closed by singhkay** 2016-05-18 22:50 UTC
Labels: bug

**Comment by lmillott** [comment] 2016-05-19 19:44
I just checked my template again and I found my issue.
I had placed the "diagnostics settings" resource in the wrong place in the JSON structure. This didn't give me any validation errors when I deployed it, it just deployed happily without configuring diagnostics.
It would be great if the deployment would throw so I knew there was something wrong with my template.
Here's the template config that caused the issue. Notice that my diagnostics settings resources is inside the "properties" node of the redis resource, rather than at the root. When I copied the diagnostic config in there I must have just placed it in the wrong spot.

"resources": [
    {
      "apiVersion": "2015-08-01",
      "type": "Microsoft.Cache/Redis",
      "name": "[variables('cacheName')]",
      "location": "[variables('location')]",
      "properties": {
        "enableNonSslPort": true,
        "redisVersion": "3.0",
        "sku": {
          "capacity": 1,
          "family": "C",
          "name": "Standard"
        },
        "resources": [
          {
            "apiVersion": "2015-07-01",
            "type": "Microsoft.Cache/redis/providers/diagnosticsettings",
            "name": "[concat(variables('cacheName'), '/Microsoft.Insights/service')]", 
            "location": "location",
            "dependsOn": [
              "[concat('Microsoft.Cache/Redis/', variables('cacheName'))]",
              "[concat('Microsoft.Storage/storageAccounts/', variables('storageAccountName'))]"
              
            ],
            "properties": {
              "status": "ON",
              "storageAccountName": "[variables('storageAccountName')]"
            }
          }
        ]
      }
    }
  ]


Thanks, and sorry for wasting your time trying to repro it.

**Comment by singhkay** [comment] 2016-05-19 19:56
@lmillott No worries, glad you got it figured out

**Comment by Pedroms1** [comment] 2019-08-29 10:33
Hello,

This just happened to a customer of mine.

There definitely is a bug, as even today, there is no validation error, despite this being a very different from what is designed in the schema.

Can you please reopen this as a bug?
