### ISSUE TITLE
ISE ARM Template Deploy to Azure Link

### ISSUE THREAD

**Issue by kantkrish** [Azure/azure-quickstart-templates#8397] opened 2020-10-07 20:34 UTC
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

While tryin to use the ARM template "Deploy To Azure" for ISE deployment, it fails with the error message " Service Not Available".
 

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[201-integration-service-environment]
(https://github.com/Azure/azure-quickstart-templates/tree/master/201-integration-service-environment)

### Issue Details
While tryin to use the ARM template "Deploy To Azure" for ISE deployment, it fails with the error message " Service Not Available".
 
### Repro steps (*if necessary, delete otherwise*)
1.
2.
3.
4.
5.

**Comment by Yvand** [comment] 2020-10-08 08:49
It's possibly a duplicate of https://github.com/Azure/azure-quickstart-templates/issues/8288
Can you try using the same format for the URI as in comment https://github.com/Azure/azure-quickstart-templates/issues/8288#issuecomment-703684266?

**Comment by bmoore-msft** [comment] 2020-10-22 02:28
Thx Yvand...

**Closed by bmoore-msft** 2020-10-22 02:28 UTC
