### ISSUE TITLE
101-vm-user-image-data-disks Getting error: StorageAccountTypeNotSupported

### ISSUE THREAD

**Issue by gauthamr05** [Azure/azure-quickstart-templates#2788] opened 2016-11-22 11:09 UTC
After trying to deploy 101-vm-user-image-data-disks I got the following error message:

"code": "StorageAccountTypeNotSupported",
"message": "Storage account <xxxxx> is of Premium_LRS type. Boot Diagnostics supports Standard_GRS,Standard_LRS,Standard_RAGRS storage account types."

I am deploying in to existing resource group where my OS and Data disk images reside in single storage account. Input osDiskVhdUri is the Image uri provided in the json while creating an Image.

ref to create Image: https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-capture-image

Could you help me with the same?

**Comment by MCKLMT** [comment] 2016-11-27 19:17
I just submitted a pull request (#2803 ) to fix this issue.

**Comment by MCKLMT** [comment] 2016-12-01 08:27
The pull request has been merged. You can check if the issue is fixed on your side and close the issue.

**Comment by gauthamr05** [comment] 2016-12-05 06:11
HI MCKLMT,

Thanks for the resolution but I'm facing the same problem for 101-vm-from-user-image and majorly : 201-vmss-linux-nat. 
In 201-vmss-linux-nat I have defined 'image.uri' instead of 'vhdContainers' under 'virtualMachineProfile'.

The idea is to create a VM scale set with a load balancer, nat rules and bring up the instances using the VM image created.

**Comment by MCKLMT** [comment] 2016-12-05 08:08
I deployed the template 101-vm-user-image-data-disks with no issues. 
What are you trying to achieve?
This template is not intended to create a VMSS.

**Comment by gauthamr05** [comment] 2016-12-05 08:11
I posted the issue wrongly. I'm trying to create a VMSS using a VM image, was trying to use 201-vmss-linux-nat for this.

While doing this I was facing error as : Storage account is of Premium_LRS type. Boot Diagnostics supports Standard_GRS,Standard_LRS,Standard_RAGRS storage account types.

In 201-vmss-linux-nat I have defined 'image.uri' instead of 'vhdContainers' under 'virtualMachineProfile'.

**Comment by MCKLMT** [comment] 2016-12-05 08:14
Please close this issue and open another one with all the informations to reproduce it.

**Closed** 2016-12-05 08:14 UTC

**Comment by gauthamr05** [comment] 2016-12-05 08:19
Created a new issue. PFB the link:
https://github.com/Azure/azure-quickstart-templates/issues/2819
