### ISSUE TITLE
Improve documentation about username and password requirements (All VM creation actions fail)

### ISSUE THREAD

**Issue by tfnaylor** [Azure/azure-quickstart-templates#380] opened 2015-07-09 18:45 UTC
I have tried several quickstart templates using the Deploy to Azure button and all fail on the VM creation step (both Linux and Windows VM's fail in the same way). It is a Bad Request failure so it seems impossible to diagnose. All other resources defined in the templates are created. Is it possible that the API version has recently gotten out of sync?

**Comment by tfnaylor** [comment] 2015-07-09 21:09
I think I may have figured this out - at least for the templates that include a Linux VM. It turns out that the administrator password (a property in most/all of these templates) has minimum requirements. If you don't get this right you get a Bad Request response but no indication that it had to do with the admin password.

NOTE TO ALL TEMPLATE AUTHORS: Please use the metadata element (or just note it in the readme) to describe the minimum password requirements to successfully create a VM.

**Comment by aculich** [comment] 2015-07-10 03:12
Two other failure modes I experienced are:

- If you set the username from the default `azureuser` to something (seemingly) illegal like `admin`, it fails (but with an unhelpful error message)
- If the password exceeds other limits (I am not sure where they are defined). In my case, I had auto-generated a 32 character password that fit the minimum complexity requirements, but apparently that was too long. I shortened it to a 16 character password and it works (after also figuring out the above username problem that was confounding my tests of your original suggestion.

**Comment by rgardler** [comment] 2015-07-10 07:28
This is great feedback. Thank you both. I'm marking this issue as an enhancement as we should include this in documentation one day.

**Comment by bingosummer** [comment] 2015-07-14 04:27
Same issue on the storage name parameter. A valid StorageName should not include "-" and Uppercase letters.
Does the template provide a validation method? If not, we can only expect Azure Portal to validate the parameters.

**Comment by rgardler** [comment] 2015-07-26 23:18
There is a related issue (asking for parameter validation) on the Azure portal User Voice site: http://feedback.azure.com/forums/223579-azure-preview-portal/suggestions/8622784-resource-group-template-parameter-validation#comments

**Comment by bingosummer** [comment] 2015-09-24 08:34
Hi @rgardler , any further comment on this?

**Comment by rossf7** [comment] 2015-11-05 14:25
I've also had this problem with the password rules when launching the mesos-swarm-marathon template. Being new to Azure it took a while for me to track down the cause.

It would be great if there was a help message with the validation rules. Or ideally if this was validated before the template is launched.

**Comment by singhkay** [comment] 2015-11-05 19:18
@rossf7 Fair point, we're seeing failures where folks enter the wrong inputs which leads to template deployment failures. Adding @rjmax from the ARM team to see if they are working on early validation of input parameters

**Comment by rgardler** [comment] 2015-11-06 00:44
Perhaps we can provide the rl

**Comment by rgardler** [comment] 2015-11-06 00:46
Damn it... clumsy fingers on a touch screen, didn't mean to close, meant to say...

Perhaps we can provide guidance in the best practice doc and also encourage template authors to include the guidance in their parameter descriptions.

**Comment by singhkay** [comment] 2016-04-08 21:24
Closing as early validation is now live in template deployment workflow.

**Closed by singhkay** 2016-04-08 21:24 UTC
Labels: enhancement/feature

**Comment by blueelvis** [comment] 2017-07-12 11:55
@singhkays - So, can we specify regex or things like that before deployment for template validation inside the JSON Template to check parameters and their values to ensure that they are in the correct format?

**Comment by softwarecraft** [comment] 2019-09-06 18:39
@singhkays please clarify your comment. I don't find this is an adequate substitute for validation on template parameters. Many "languages" or schemas provide that, eg a regex expression.

> Closing as early validation is now live in template deployment workflow.
